# version: '3.10'
services:
  db: 
    image: postgres:15
    container_name: pg_database
    expose:
      - 1221
    env_file:
      - .env-prod
    ports:
      - 1221:5432
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - google_sheets_bot

  oauth_app:
    build: 
      context: .
    env_file: 
    - .env-prod
    container_name: oauth_app
    command: ["/code/docker/app.sh"]
    ports:
    - 80:80
    environment:
      - FASTAPI_HOST=http://127.0.0.1:80
      - DATABASE_URL=${DATABASE_URL}
      - PGDATA=/var/lib/postgresql/data/pgdata
    depends_on:
    - db
    networks:
      - google_sheets_bot

  bot_app:
    build:
      context: .
    env_file: 
    - .env-prod
    container_name: tg_bot
    command: ["/code/docker/bot.sh"]
    environment:
      - FASTAPI_HOST=http://127.0.0.1:80
      # - DATABASE_URL=${DATABASE_URL}
      - PGDATA=/var/lib/postgresql/data/pgdata
    depends_on:
    - db
    - oauth_app
    networks:
      - google_sheets_bot
networks: # явно объявленные сети
  google_sheets_bot:

volumes:
  pgdata:
    driver: local


  