# This is a basic example Blueprint for a Django web service and
# the PostgreSQL database it connects to.
services:
  - type: web # A Python web service named django-app running on a free instance
    plan: free
    name: fastapi_app
    runtime: python
    repo: https://github.com/CyberWarrior91/google_sheets_tg_bot.git
    buildCommand: "./docker/app_build.sh"
    startCommand: "./docker/app.sh"
    envVars:
      - key: DATABASE_URL # Sets DATABASE_URL to the connection string of the django-app-db database
        fromDatabase:
          name: google_bot_db
          property: connectionString
      - key: FASTAPI_HOST
        value: https://google-sheets-tg-bot.onrender.com
      - key: OAUTHLIB_INSECURE_TRANSPORT
        value: 0
      - key: SECRET_KEY
        generateValue: true
      - key: BOT_URL
        sync: false
      - key: DEBUG
        value: false

  - type: worker
    plan: starter
    name: telegram_bot
    runtime: python
    repo: https://github.com/CyberWarrior91/google_sheets_tg_bot.git
    buildCommand: "./docker/app_build.sh"
    startCommand: "./docker/bot.sh"
    envVars:
      - key: DATABASE_URL # Sets DATABASE_URL to the connection string of the django-app-db database
        fromDatabase:
          name: google_bot_db
          property: connectionString
      - key: BOT_TOKEN
        sync: false
      
databases:
  - name: google_bot_db # A PostgreSQL database named django-app-db running on a free instance
    plan: free
